config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'homes#top'
  
  get 'books' =>'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  put 'books/:id' => 'books#update'
  delete 'books/:id' => 'books#destroy'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def index
  @books = Book.all
  @book = Book.new
end

def show
  @book = Book.find(params[:id])
end


def create
  @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
end
end

def edit
  @book = Book.find(params[:id])
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
     flash[:notice] = "Book was successfully updated."
     redirect_to book_path(@book.id)
  else
     render :edit


end
end

def destroy
  @book = Book.find(params[:id])
  if @book.destroy
      flash[:notice] = "Book was successfully destroyed."
  redirect_to books_path
end
end

private
def book_params
params.require(:book).permit(:title, :body)
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

<p>  
<%= f.submit 'Update Book' %>
<% end %>
</p>

<%= link_to "show", book_path(@book.id) %>
|
<a class="back" href="/books">Back</a>
  

app/views/books/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>


<!DOCTYPE html>
<html>

　<body>

    <h1>Books</h1>

<table>

<thead>
  <tr>
   <th>title</th>
   <th>body</th>
   <th></th>
 </tr>
</thead>

<tbody>
    
<% @books.each do |book| %>
<tr>
   <td><%= book.title %></td>
   <td><%= book.body %></td>
   <td>
   <%= link_to "Show", book_path(book.id) %>
   <%= link_to "Edit", edit_book_path(book.id) %>
   <%= link_to "Destroy", update_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
   
   </td>
 </tr>
 <% end %>


</tbody>
</table>

<h3>New book</h3>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
 <% end %>
<% end %>


<%= form_with model: @book, url:'/books', local:true do |f| %>


<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>

<% end %>


</form>
</body>
</html>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

<p>
<strong>Title:</strong>
<%= @book.title %>
</p>

<p>
<strong>Body:</strong>
<%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<a class="back" href="/books">Back</a>

app/views/homes/top.html.erb
<html>

<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
  </h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p>印象を共有し交換することができます</p>

<p>
  <a href="/books">start</a>
</p>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
   